// Demo data for testing admin dashboard without backend

export const DEMO_DOCTORS = [
  {
    _id: "demo-doc-1",
    name: "Dr. Sarah Johnson",
    email: "sarah.johnson@hospital.com",
    phone: "+1 234 567 8901",
    specialization: "Cardiology",
    experience: 15,
    qualification: "MD, FACC",
    consultationFee: 500,
    opdTimings: "Mon-Fri: 9 AM - 5 PM",
    language: ["English", "Spanish"],
    bio: "Board-certified cardiologist with expertise in interventional cardiology and heart failure management.",
    profilePicture: "/experienced-male-cardiologist-doctor-professional-.jpg",
    isActive: true,
  },
  {
    _id: "demo-doc-2",
    name: "Dr. Emily Chen",
    email: "emily.chen@hospital.com",
    phone: "+1 234 567 8902",
    specialization: "Neurology",
    experience: 12,
    qualification: "MD, PhD",
    consultationFee: 600,
    opdTimings: "Mon-Wed: 10 AM - 4 PM",
    language: ["English", "Mandarin"],
    bio: "Neurologist specializing in movement disorders and neurodegenerative diseases.",
    profilePicture: "/asian-female-neurologist-doctor-professional-intel.jpg",
    isActive: true,
  },
  {
    _id: "demo-doc-3",
    name: "Dr. Michael Roberts",
    email: "michael.roberts@hospital.com",
    phone: "+1 234 567 8903",
    specialization: "Pediatrics",
    experience: 10,
    qualification: "MD, FAAP",
    consultationFee: 400,
    opdTimings: "Mon-Sat: 8 AM - 6 PM",
    language: ["English", "French"],
    bio: "Pediatrician dedicated to providing comprehensive care for children of all ages.",
    profilePicture: "/asian-male-pediatrician-doctor-gentle-professional.jpg",
    isActive: true,
  },
  {
    _id: "demo-doc-4",
    name: "Dr. Jessica Martinez",
    email: "jessica.martinez@hospital.com",
    phone: "+1 234 567 8904",
    specialization: "Orthopedics",
    experience: 8,
    qualification: "MD, MS Ortho",
    consultationFee: 450,
    opdTimings: "Tue-Sat: 9 AM - 5 PM",
    language: ["English", "Spanish"],
    bio: "Orthopedic surgeon specializing in sports medicine and joint replacement.",
    profilePicture: "/placeholder.svg?height=100&width=100",
    isActive: false,
  },
]

export const DEMO_SPECIALIZATIONS = [
  {
    _id: "demo-spec-1",
    name: "Cardiology",
    description: "Diagnosis and treatment of heart and cardiovascular diseases",
    icon: "❤️",
    isActive: true,
  },
  {
    _id: "demo-spec-2",
    name: "Neurology",
    description: "Treatment of disorders of the nervous system and brain",
    icon: "🧠",
    isActive: true,
  },
  {
    _id: "demo-spec-3",
    name: "Pediatrics",
    description: "Medical care for infants, children, and adolescents",
    icon: "👶",
    isActive: true,
  },
  {
    _id: "demo-spec-4",
    name: "Orthopedics",
    description: "Treatment of musculoskeletal system disorders",
    icon: "🦴",
    isActive: true,
  },
  {
    _id: "demo-spec-5",
    name: "Dermatology",
    description: "Diagnosis and treatment of skin, hair, and nail conditions",
    icon: "🩺",
    isActive: true,
  },
  {
    _id: "demo-spec-6",
    name: "Ophthalmology",
    description: "Eye and vision care services",
    icon: "👁️",
    isActive: false,
  },
]

export const DEMO_APPOINTMENTS = [
  {
    _id: "demo-appt-1",
    patientName: "John Smith",
    patientEmail: "john.smith@email.com",
    patientPhone: "+1 234 567 1001",
    patientAge: 45,
    doctorId: "demo-doc-1",
    doctorName: "Dr. Sarah Johnson",
    specialization: "Cardiology",
    appointmentDate: "2024-01-15",
    appointmentTime: "10:00 AM",
    status: "confirmed",
    symptoms: "Chest pain and shortness of breath",
    createdAt: "2024-01-10",
  },
  {
    _id: "demo-appt-2",
    patientName: "Maria Garcia",
    patientEmail: "maria.garcia@email.com",
    patientPhone: "+1 234 567 1002",
    patientAge: 32,
    doctorId: "demo-doc-2",
    doctorName: "Dr. Emily Chen",
    specialization: "Neurology",
    appointmentDate: "2024-01-16",
    appointmentTime: "2:00 PM",
    status: "pending",
    symptoms: "Persistent headaches and dizziness",
    createdAt: "2024-01-11",
  },
  {
    _id: "demo-appt-3",
    patientName: "David Lee",
    patientEmail: "david.lee@email.com",
    patientPhone: "+1 234 567 1003",
    patientAge: 8,
    doctorId: "demo-doc-3",
    doctorName: "Dr. Michael Roberts",
    specialization: "Pediatrics",
    appointmentDate: "2024-01-17",
    appointmentTime: "11:30 AM",
    status: "completed",
    symptoms: "Fever and cough for 3 days",
    createdAt: "2024-01-12",
  },
  {
    _id: "demo-appt-4",
    patientName: "Sarah Johnson",
    patientEmail: "sarah.j@email.com",
    patientPhone: "+1 234 567 1004",
    patientAge: 28,
    doctorId: "demo-doc-1",
    doctorName: "Dr. Sarah Johnson",
    specialization: "Cardiology",
    appointmentDate: "2024-01-18",
    appointmentTime: "3:30 PM",
    status: "cancelled",
    symptoms: "Regular checkup",
    createdAt: "2024-01-13",
  },
]

export const DEMO_PATIENTS = [
  {
    _id: "demo-patient-1",
    name: "John Smith",
    email: "john.smith@email.com",
    phone: "+1 234 567 1001",
    age: 45,
    gender: "Male",
    bloodGroup: "O+",
    address: "123 Main Street, New York, NY 10001",
    emergencyContact: "+1 234 567 9999",
    registeredDate: "2023-06-15",
    totalVisits: 5,
    lastVisit: "2024-01-15",
    medicalHistory: ["Hypertension", "Type 2 Diabetes"],
  },
  {
    _id: "demo-patient-2",
    name: "Maria Garcia",
    email: "maria.garcia@email.com",
    phone: "+1 234 567 1002",
    age: 32,
    gender: "Female",
    bloodGroup: "A+",
    address: "456 Oak Avenue, Los Angeles, CA 90001",
    emergencyContact: "+1 234 567 8888",
    registeredDate: "2023-08-20",
    totalVisits: 3,
    lastVisit: "2024-01-16",
    medicalHistory: ["Migraine", "Anxiety"],
  },
  {
    _id: "demo-patient-3",
    name: "David Lee",
    email: "david.lee@email.com",
    phone: "+1 234 567 1003",
    age: 8,
    gender: "Male",
    bloodGroup: "B+",
    address: "789 Pine Road, Chicago, IL 60601",
    emergencyContact: "+1 234 567 7777",
    registeredDate: "2023-11-10",
    totalVisits: 7,
    lastVisit: "2024-01-17",
    medicalHistory: ["Asthma", "Seasonal Allergies"],
  },
  {
    _id: "demo-patient-4",
    name: "Sarah Johnson",
    email: "sarah.j@email.com",
    phone: "+1 234 567 1004",
    age: 28,
    gender: "Female",
    bloodGroup: "AB+",
    address: "321 Elm Street, Houston, TX 77001",
    emergencyContact: "+1 234 567 6666",
    registeredDate: "2024-01-05",
    totalVisits: 2,
    lastVisit: "2024-01-18",
    medicalHistory: [],
  },
  {
    _id: "demo-patient-5",
    name: "Robert Williams",
    email: "robert.w@email.com",
    phone: "+1 234 567 1005",
    age: 56,
    gender: "Male",
    bloodGroup: "O-",
    address: "654 Maple Drive, Miami, FL 33101",
    emergencyContact: "+1 234 567 5555",
    registeredDate: "2023-03-12",
    totalVisits: 12,
    lastVisit: "2024-01-10",
    medicalHistory: ["Heart Disease", "High Cholesterol", "Arthritis"],
  },
]

export const DEMO_BANNERS = [
  {
    _id: "demo-banner-1",
    title: "Advanced Medical Technology at Your Service",
    description:
      "Experience world-class healthcare with our state-of-the-art medical equipment and cutting-edge treatment protocols.",
    image: "/professional-doctor-consulting-with-happy-family-i.jpg",
    buttonText: "Book Appointment",
    buttonLink: "/book",
    isActive: true,
    order: 1,
  },
  {
    _id: "demo-banner-2",
    title: "24/7 Emergency Care When You Need It Most",
    description:
      "Our emergency department is always ready to provide immediate care with experienced specialists available around the clock.",
    image: "/experienced-male-cardiologist-doctor-professional-.jpg",
    buttonText: "Learn More",
    buttonLink: "/services",
    isActive: true,
    order: 2,
  },
  {
    _id: "demo-banner-3",
    title: "Compassionate Care for Your Entire Family",
    description:
      "From pediatrics to geriatrics, we offer comprehensive healthcare services tailored to every member of your family.",
    image: "/asian-male-pediatrician-doctor-gentle-professional.jpg",
    buttonText: "View Services",
    buttonLink: "/services",
    isActive: true,
    order: 3,
  },
]
